// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzOztDHcOnl-S6nUaxJfUtE2T6_Dp6vME',
    appId: '1:40436076622:web:cba99ddce588ed359c731f',
    messagingSenderId: '40436076622',
    projectId: 'budgettracker-bfe03',
    authDomain: 'budgettracker-bfe03.firebaseapp.com',
    storageBucket: 'budgettracker-bfe03.appspot.com',
    measurementId: 'G-16VDMGL2NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9gvcgpUOSKhuumJUARpdyIqa-qVa_y-s',
    appId: '1:40436076622:android:da2dc9d24e0f5d539c731f',
    messagingSenderId: '40436076622',
    projectId: 'budgettracker-bfe03',
    storageBucket: 'budgettracker-bfe03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdOwaPSkrlcHfpGAXayRCjPLKETDBz3oQ',
    appId: '1:40436076622:ios:8c9b205f2986f08a9c731f',
    messagingSenderId: '40436076622',
    projectId: 'budgettracker-bfe03',
    storageBucket: 'budgettracker-bfe03.appspot.com',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdOwaPSkrlcHfpGAXayRCjPLKETDBz3oQ',
    appId: '1:40436076622:ios:8c9b205f2986f08a9c731f',
    messagingSenderId: '40436076622',
    projectId: 'budgettracker-bfe03',
    storageBucket: 'budgettracker-bfe03.appspot.com',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzOztDHcOnl-S6nUaxJfUtE2T6_Dp6vME',
    appId: '1:40436076622:web:e643a3c9e2856c649c731f',
    messagingSenderId: '40436076622',
    projectId: 'budgettracker-bfe03',
    authDomain: 'budgettracker-bfe03.firebaseapp.com',
    storageBucket: 'budgettracker-bfe03.appspot.com',
    measurementId: 'G-KVWT2BKSGG',
  );

}